spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#不配置,默认属性也是这样,从eureka拉取路径自动配置下面的路径
#zuul的路由配置  ,访问路径
#zuul:
 # routes:
  #  item-service: /item-service/**  
    #可以配置为访问a路径底层访问item-service的配置item-service: /a/**  
   # user-service: /user-service/**
    #order-service: /order-service/**
  
#需要开启重试，默认不开启 
zuul:
  retryable: true #默认是关闭的

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
#降低 hystrix 超时时间，以便测试降级
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
#zuul 已经包含 actuator 依赖  ,暴露监控端点         
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    